# Generated by Django 3.1.4 on 2020-12-29 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201229_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('date_of_birth', models.DateField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('citizenship', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True, max_length=255)),
                ('languages', models.TextField(blank=True, max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_site', models.URLField(blank=True)),
                ('company_info', models.TextField(blank=True)),
                ('company_scope', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
