# Generated by Django 3.1.4 on 2020-12-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
