# Generated by Django 3.1.4 on 2020-12-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201229_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
