# Generated by Django 3.1.4 on 2021-01-10 15:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210106_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='speciality',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company_scope',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('BLR', 'Republic of Belarus'), ('RUS', 'The Russian Federation'), ('UKR', 'Ukraine'), ('LTU', 'Lithuania'), ('LVA', 'Latvia'), ('POL', 'Poland'), ('EST', 'Estonia')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('SE', 'Secondary education'), ('AD', 'Associate’s degree'), ('BD', 'Bachelor’s degree'), ('MD', 'Master’s degree'), ('DD', 'Doctoral degree')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('RU', 'Russian'), ('BY', 'Belorussian'), ('EN', 'English'), ('UA', 'Ukrainian'), ('LV', 'Lithuanian'), ('LT', 'Latvian'), ('PL', 'Polish'), ('EE', 'Estonian'), ('DE', 'German'), ('FR', 'French'), ('ES', 'Spanish'), ('CH', 'Chinese'), ('JP', 'Japanese')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Belarus', (('Brest', 'Brest'), ('Grodno', 'Grodno'), ('Gomel', 'Gomel'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'))), ('Russia', (('Moscow', 'Moscow'),)), ('Poland', (('Warsaw', 'Warsaw'),)), ('Ukraine', (('Kiev', 'Kiev'),)), ('Lithuania', (('Vilnius', 'Vilnius'),)), ('Latvia', (('Riga', 'Riga'),)), ('Estonia', (('Tallinn', 'Tallinn'),))], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', 'Driving Licence B'), ('Stress tolerance', 'Strees Tolerance'), ('MS Office', 'Ms Office'), ('Grammatically correct speech', 'Grammatically Correct Speech'), ('Teamwork', 'Teamwork'), ('Literacy', 'Literacy'), ('Corporate ethics', 'Corporate Ethics'), ('Negotiation', 'Negotiation')], max_length=50, null=True),
        ),
    ]
