# Generated by Django 3.1.4 on 2021-01-10 17:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210110_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('Belarus', 'Republic of Belarus'), ('Russia', 'The Russian Federation'), ('Ukraine', 'Ukraine'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Poland', 'Poland'), ('Estonia', 'Estonia')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('secondary', 'Secondary education'), ('associate', 'Associate’s degree'), ('bachelor', 'Bachelor’s degree'), ('master', 'Master’s degree'), ('doctoral', 'Doctoral degree')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('russian', 'Russian'), ('belarussian', 'Belorussian'), ('english', 'English'), ('ukrainian', 'Ukrainian'), ('lithuanian', 'Lithuanian'), ('latvian', 'Latvian'), ('polish', 'Polish'), ('estonian', 'Estonian'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('japanese', 'Japanese')], max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('driving_licence_b', 'Driving Licence B'), ('strees_tolerance', 'Stress tolerance'), ('ms_office', 'MS Office'), ('grammatically_correct_speech', 'Grammatically correct speech'), ('teamwork', 'Teamwork'), ('literacy', 'Literacy'), ('corporate_ethics', 'Corporate ethics'), ('negotiation', 'Negotiation')], max_length=120, null=True),
        ),
    ]
