# Generated by Django 3.1.4 on 2021-01-12 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210110_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('now', models.BooleanField()),
                ('end', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('company_site', models.URLField(blank=True, null=True)),
                ('company_spheres', multiselectfield.db.fields.MultiSelectField(choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91)),
                ('position', models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], max_length=50)),
                ('responsibilities', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
