# Generated by Django 3.1.4 on 2021-01-13 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210112_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='users/%Y/%m/%d')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('Belarus', (('Brest', 'Brest'), ('Grodno', 'Grodno'), ('Gomel', 'Gomel'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'))), ('Russia', (('Moscow', 'Moscow'),)), ('Poland', (('Warsaw', 'Warsaw'),)), ('Ukraine', (('Kiev', 'Kiev'),)), ('Lithuania', (('Vilnius', 'Vilnius'),)), ('Latvia', (('Riga', 'Riga'),)), ('Estonia', (('Tallinn', 'Tallinn'),))], default='', max_length=50)),
                ('citizenship', models.CharField(blank=True, choices=[('Republic of Belarus', 'Republic of Belarus'), ('Russian Federation', 'Russian Federation'), ('Ukraine', 'Ukraine'), ('Republic of Lithuania', 'Republic of Lithuania'), ('Republic of Latvia', 'Republic of Latvia'), ('Republic of Poland', 'Republic of Poland'), ('Republic of Estonia', 'Republic of Estonia')], default='', max_length=50)),
                ('education', models.CharField(blank=True, choices=[('high school', 'Hight school diploma'), ('associate', 'Associate’s degree'), ('bachelor', 'Bachelor’s degree'), ('master', 'Master’s degree'), ('doctoral', 'Doctoral degree')], default='', max_length=11)),
                ('specialization', models.CharField(blank=True, choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], default='', max_length=50)),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('driving_licence_b', 'Driving Licence B'), ('strees_tolerance', 'Stress tolerance'), ('ms_office', 'MS Office'), ('grammatically_correct_speech', 'Grammatically correct speech'), ('teamwork', 'Teamwork'), ('literacy', 'Literacy'), ('corporate_ethics', 'Corporate ethics'), ('negotiation', 'Negotiation')], max_length=120, null=True)),
                ('languages', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('russian', 'Russian'), ('belarussian', 'Belorussian'), ('english', 'English'), ('ukrainian', 'Ukrainian'), ('lithuanian', 'Lithuanian'), ('latvian', 'Latvian'), ('polish', 'Polish'), ('estonian', 'Estonian'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('chinese', 'Chinese'), ('japanese', 'Japanese')], max_length=111, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('info', models.TextField(blank=True, default='')),
                ('spheres', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], max_length=50)),
                ('salary', models.PositiveSmallIntegerField()),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('conditions', models.TextField()),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app.employeer')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='employeer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employeer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
