# Generated by Django 3.1.4 on 2021-01-14 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210114_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.AddField(
            model_name='employeer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employeers/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.applicant'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='applicants/%Y/%m/%d'),
        ),
    ]
