# Generated by Django 3.1.4 on 2021-01-14 00:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210114_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91, null=True),
        ),
    ]
