# Generated by Django 3.1.4 on 2021-01-14 03:20

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210114_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='begin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='now',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
