# Generated by Django 3.1.4 on 2021-01-14 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210114_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.applicant'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='begin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], default='', max_length=91),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(choices=[('economist', 'Economist'), ('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('seller', 'Seller'), ('manager', 'Manager')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
