# Generated by Django 3.1.4 on 2021-01-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210115_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['id']},
        ),
    ]
