# Generated by Django 3.1.4 on 2021-01-16 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210116_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='employers/%Y/%m/%d')),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('company_site', models.URLField(null=True)),
                ('company_info', models.TextField(default='')),
                ('company_spheres', multiselectfield.db.fields.MultiSelectField(choices=[('energetics', 'Energetics'), ('financial_sector', 'Financial sector'), ('chemical_industry', 'The chemical industry'), ('art', 'Art and culture'), ('education', 'Education'), ('medecine', 'Medicine'), ('retail', 'Retail'), ('car_business', 'Car business'), ('it', 'Information Technology')], max_length=91, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='employeer',
        ),
        migrations.DeleteModel(
            name='Employeer',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
