# Generated by Django 3.1.4 on 2021-01-17 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210116_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField()),
                ('position', models.CharField(max_length=100)),
                ('need_exp', models.CharField(choices=[('+-', 'Does not matter'), ('-', 'No experience'), ('1-3', 'From 1 to 3 years'), ('1-6', 'From 3 to 6 years'), ('6+', 'Over 6 years')], max_length=50)),
                ('salary', models.PositiveSmallIntegerField(null=True)),
                ('body', models.TextField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app.employer')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
