# Generated by Django 3.1.6 on 2021-02-14 01:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210117_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(choices=[(None, '------------'), ('Republic of Belarus', 'Republic of Belarus'), ('Russian Federation', 'Russian Federation'), ('Ukraine', 'Ukraine'), ('Republic of Lithuania', 'Republic of Lithuania'), ('Republic of Latvia', 'Republic of Latvia'), ('Republic of Poland', 'Republic of Poland'), ('Republic of Estonia', 'Republic of Estonia')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[(None, '------------'), ('High school', 'Hight school diploma'), ('Associate', 'Associate’s degree'), ('Bachelor', 'Bachelor’s degree'), ('Master', 'Master’s degree'), ('Doctoral', 'Doctoral degree')], default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Russian', 'Russian'), ('Belarussian', 'Belarussian'), ('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Lithuanian', 'Lithuanian'), ('Latvian', 'Latvian'), ('Polish', 'Polish'), ('Estonian', 'Estonian'), ('German', 'German'), ('French', 'French'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese')], max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(choices=[(None, '------------'), ('Belarus', (('Brest', 'Brest'), ('Grodno', 'Grodno'), ('Gomel', 'Gomel'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'))), ('Russia', (('Moscow', 'Moscow'),)), ('Poland', (('Warsaw', 'Warsaw'),)), ('Ukraine', (('Kiev', 'Kiev'),)), ('Lithuania', (('Vilnius', 'Vilnius'),)), ('Latvia', (('Riga', 'Riga'),)), ('Estonia', (('Tallinn', 'Tallinn'),))], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('driving licence B', 'Driving licence B'), ('strees_tolerance', 'Stress tolerance'), ('ms_office', 'MS Office'), ('grammatically_correct_speech', 'Grammatically correct speech'), ('teamwork', 'Teamwork'), ('literacy', 'Literacy'), ('corporate_ethics', 'Corporate ethics'), ('negotiation', 'Negotiation')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='specialization',
            field=models.CharField(choices=[(None, '------------'), ('Economist', 'Economist'), ('Lawyer', 'Lawyer'), ('Engineer', 'Engineer'), ('Architect', 'Architect'), ('Teacher', 'Teacher'), ('Driver', 'Driver'), ('Cook', 'Cook'), ('Seller', 'Seller'), ('Manager', 'Manager')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_info',
            field=models.TextField(default='Something about the company. History, goals, missions, values, features, advantages, etc.'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Energetics', 'Energetics'), ('Financial_sector', 'Financial sector'), ('Chemical_industry', 'The chemical industry'), ('Art and culture', 'Art and culture'), ('Education', 'Education'), ('Medecine', 'Medicine'), ('Retail', 'Retail'), ('Car_business', 'Car business'), ('IT', 'IT')], max_length=103, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Energetics', 'Energetics'), ('Financial_sector', 'Financial sector'), ('Chemical_industry', 'The chemical industry'), ('Art and culture', 'Art and culture'), ('Education', 'Education'), ('Medecine', 'Medicine'), ('Retail', 'Retail'), ('Car_business', 'Car business'), ('IT', 'IT')], max_length=103),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Traineeship', 'Traineeship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='need_exp',
            field=models.CharField(choices=[('Not required', 'No experience'), ('1-3 years', 'From 1 to 3 years'), ('1-6 years', 'From 3 to 6 years'), ('Over 6 years', 'Over 6 years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule'), ('Remote work', 'Remote work')], max_length=100),
        ),
    ]
