# Generated by Django 3.1.6 on 2021-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210228_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='BYN', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_site',
            field=models.URLField(default='https://'),
        ),
    ]
