# Generated by Django 3.1.6 on 2021-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20210228_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[(None, '------------'), ('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='need_exp',
            field=models.CharField(choices=[(None, '------------'), ('Not required', 'No experience'), ('1-3 years', 'From 1 to 3 years'), ('1-6 years', 'From 3 to 6 years'), ('Over 6 years', 'Over 6 years')], max_length=50),
        ),
    ]
