# Generated by Django 3.1.6 on 2021-04-04 23:03

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210405_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Соискаитель', 'verbose_name_plural': 'Соискаители'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Работодатель', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['id'], 'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-published'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(verbose_name='Активная вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='body',
            field=models.TextField(verbose_name='Текст вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[(None, '------------'), ('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Traineeship', 'Traineeship')], max_length=100, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='need_exp',
            field=models.CharField(choices=[(None, '------------'), ('Not required', 'No experience'), ('1-3 years', 'From 1 to 3 years'), ('1-6 years', 'From 3 to 6 years'), ('Over 6 years', 'Over 6 years')], max_length=50, verbose_name='Требуемый опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Уровень з/п'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Full day', 'Full day'), ('Shift work', 'Shift work'), ('Flexible schedule', 'Flexible schedule'), ('Remote work', 'Remote work')], max_length=100, verbose_name='График работы'),
        ),
    ]
