# Generated by Django 3.1.6 on 2021-04-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210405_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app.employer', verbose_name='Работадатель'),
        ),
    ]
