# Generated by Django 3.1.6 on 2021-04-12 02:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210412_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('trainee', 'Стажировка')], max_length=100, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full', 'Полный день'), ('shift', 'Сменный график'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа')], max_length=100, verbose_name='График работы'),
        ),
    ]
