# Generated by Django 3.1.6 on 2021-04-12 17:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210412_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('traineeship', 'Стажировка')], max_length=100, verbose_name='Тип занятости'),
        ),
    ]
