# Generated by Django 3.1.6 on 2021-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20210412_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('noExperience', 'Без опыта'), ('from1To3', 'От 1 года до 3 лет'), ('from3To6', 'От 3 до 6 лет'), ('over6', 'Более 6 лет')], max_length=50, verbose_name='Требуемый опыт работы'),
        ),
    ]
