# Generated by Django 3.1.6 on 2021-04-23 02:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210412_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Russian', 'Russian'), ('Belarussian', 'Belarussian'), ('English', 'English'), ('Ukrainian', 'Ukrainian'), ('Lithuanian', 'Lithuanian'), ('Latvian', 'Latvian'), ('Polish', 'Polish'), ('Estonian', 'Estonian'), ('German', 'German'), ('French', 'French'), ('Spanish', 'Spanish'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese')], max_length=111, null=True, verbose_name='Знание языков'),
        ),
    ]
