# Generated by Django 3.1.6 on 2021-04-23 21:31

import app.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20210423_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(choices=[(None, '------------'), ('Belarus', 'Belarus'), ('Russia', 'Russia'), ('Ukraine', 'Ukraine'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Poland', 'Poland'), ('Estonia', 'Estonia')], default='', max_length=50, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(upload_to=app.services.rename_avatar, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(verbose_name='Публиковать?'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[(None, '------------'), ('BYN', 'BYN'), ('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='', max_length=3, verbose_name='Валюта'),
        ),
    ]
