# Generated by Django 3.1.6 on 2021-04-24 18:48

import app.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210424_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.services.rename_avatar, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(upload_to=app.services.rename_avatar, verbose_name='Фото'),
        ),
    ]
