# Generated by Django 3.1.6 on 2021-04-27 20:24

import app.services
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20210424_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(choices=[(None, '------------'), ('Беларусь', 'Беларусь'), ('Russia', 'Russia'), ('Ukraine', 'Ukraine'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Poland', 'Poland'), ('Estonia', 'Estonia')], default='', max_length=50, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[(None, '------------'), ('High school', 'Hight school diploma'), ("Associate's", 'Associate’s'), ('Бакалавр', 'Бакалавр'), ("Master's", 'Master’s'), ('Doctoral', 'Doctoral')], default='', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(choices=[(None, '------------'), ('Беларусь', (('Brest', 'Brest'), ('Гродно', 'Гродно'), ('Лида', 'Лида'), ('Gomel', 'Gomel'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'))), ('Russia', (('Moscow', 'Moscow'),)), ('Poland', (('Warsaw', 'Warsaw'),)), ('Ukraine', (('Kiev', 'Kiev'),)), ('Lithuania', (('Vilnius', 'Vilnius'),)), ('Latvia', (('Riga', 'Riga'),)), ('Estonia', (('Tallinn', 'Tallinn'),))], default='', max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='specialization',
            field=models.CharField(choices=[(None, '------------'), ('Экономист', 'Экономист'), ('Lawyer', 'Lawyer'), ('Инженер', 'Инженер'), ('Разработчик ПО', 'Разработчик ПО'), ('Architect', 'Architect'), ('Teacher', 'Teacher'), ('Driver', 'Driver'), ('Cook', 'Cook'), ('Seller', 'Seller'), ('Manager', 'Manager')], default='', max_length=50, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Energetics', 'Energetics'), ('Financial_sector', 'Financial sector'), ('Chemical_industry', 'The chemical industry'), ('Art and culture', 'Art and culture'), ('Education', 'Education'), ('Medecine', 'Medicine'), ('Retail', 'Retail'), ('Car_business', 'Car business'), ('ИТ', 'ИТ')], max_length=103, null=True, verbose_name='Сфера деятельности компании'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.services.rename_avatar, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Energetics', 'Energetics'), ('Financial_sector', 'Financial sector'), ('Chemical_industry', 'The chemical industry'), ('Art and culture', 'Art and culture'), ('Education', 'Education'), ('Medecine', 'Medicine'), ('Retail', 'Retail'), ('Car_business', 'Car business'), ('ИТ', 'ИТ')], max_length=103, verbose_name='Сфера деятельности компании'),
        ),
    ]
