# Generated by Django 3.1.6 on 2021-05-13 16:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20210427_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[(None, '------------'), ('Школа', 'Hight school diploma'), ('Колледж', 'Associate’s'), ('Бакалавр', 'Бакалавр'), ('Мастер', 'Master’s'), ('Доктор', 'Doctoral')], default='', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Русский', 'Русский'), ('Беларусский', 'Беларусский'), ('Английский', 'Английский'), ('Украинский', 'Украинский'), ('Литовский', 'Литовский'), ('Латвийский', 'Латвийский'), ('Польский', 'Польский'), ('Эстонский', 'Эстонский'), ('Немецкий', 'Немецкий'), ('Французский', 'Французский'), ('Испанский', 'Испанский'), ('Китайский', 'Китайский'), ('Японский', 'Японский')], max_length=500, null=True, verbose_name='Знание языков'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('driving licence B', 'Водительское удостоверение категории В'), ('strees_tolerance', 'Стрессоустойчивость'), ('ms_office', 'МС Офис'), ('grammatically_correct_speech', 'Грамотная речь'), ('teamwork', 'Командная работа'), ('literacy', 'Грамотность'), ('corporate_ethics', 'Корпоративная этика'), ('negotiation', 'Ведение переговоров'), ('driving licence B', 'Водительское удостоверение категории В'), ('strees_tolerance', 'Стрессоустойчивость'), ('ms_office', 'МС Офис'), ('grammatically_correct_speech', 'Грамотная речь'), ('teamwork', 'Командная работа'), ('literacy', 'Грамотность'), ('corporate_ethics', 'Корпоративная этика'), ('negotiation', 'Ведение переговоров')], max_length=1000, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ftime', 'Полная занятость'), ('ptime', 'Частичная занятость'), ('traineeship', 'Стажировка')], max_length=100, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fday', 'Полный день'), ('shift', 'Сменный график'), ('flexible', 'Гибкий график'), ('remote', 'Удаленная работа')], max_length=100, verbose_name='График работы'),
        ),
    ]
