# Generated by Django 3.1.6 on 2021-05-23 01:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210513_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_site',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_spheres',
        ),
        migrations.AddField(
            model_name='experience',
            name='employment',
            field=models.CharField(choices=[('ftime', 'Полная занятость'), ('ptime', 'Частичная занятость'), ('trainee', 'Стажировка'), ('profedu', 'Профессиональное обучение'), ('business', 'Предприниматель'), ('free', 'Фриланс')], default='', max_length=50, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('driving licence B', 'Водительское удостоверение категории В'), ('strees_tolerance', 'Стрессоустойчивость'), ('ms_office', 'МС Офис'), ('grammatically_correct_speech', 'Грамотная речь'), ('teamwork', 'Командная работа'), ('literacy', 'Грамотность'), ('corporate_ethics', 'Корпоративная этика'), ('negotiation', 'Ведение переговоров')], max_length=1000, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='begin',
            field=models.DateField(verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='По'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='now',
            field=models.BooleanField(blank=True, null=True, verbose_name='На данный момент я работаю в этой должности'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ftime', 'Полная занятость'), ('ptime', 'Частичная занятость'), ('trainee', 'Стажировка')], max_length=100, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('noExp', 'Без опыта'), ('from1To3', 'От 1 года до 3 лет'), ('from3To6', 'От 3 до 6 лет'), ('over6', 'Более 6 лет')], max_length=50, verbose_name='Требуемый опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fday', 'Полный день'), ('shift', 'Сменный график'), ('flex', 'Гибкий график'), ('remote', 'Удаленная работа')], max_length=100, verbose_name='График работы'),
        ),
    ]
