# Generated by Django 3.1.6 on 2021-05-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210523_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Уровень владения языком')),
            ],
            options={
                'verbose_name': 'Уровень языка',
                'verbose_name_plural': 'Уровни языков',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='languages',
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='app.applicant', verbose_name='Cоискатель')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language', verbose_name='Язык')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.langlevel', verbose_name='Уровень владения')),
            ],
            options={
                'verbose_name': 'Язык и уровень его знания',
                'verbose_name_plural': 'Языки и уровни их знаний',
            },
        ),
        migrations.AddField(
            model_name='language',
            name='level',
            field=models.ManyToManyField(related_name='languages', through='app.LanguageLevel', to='app.LangLevel', verbose_name='Уровень владения языком'),
        ),
    ]
