# Generated by Django 3.1.6 on 2021-05-24 19:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20210524_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='level',
        ),
        migrations.RemoveField(
            model_name='languagelevel',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='languagelevel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languagelevel',
            name='level',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='education',
            field=models.CharField(choices=[(None, '------------'), ('High School Diploma', 'High school diploma'), ('Associate degree', 'Associate’s degree'), ("Bachelor's degree", "Bachelor's degree"), ("Master's degree", "Master's degree"), ('Doctoral degree', 'Doctoral degree')], default='', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(choices=[(None, '------------'), ('Беларусь', (('Brest', 'Brest'), ('Hrodna', 'Hrodna'), ('Лида', 'Лида'), ('Gomel', 'Gomel'), ('Minsk', 'Minsk'), ('Mogilev', 'Mogilev'), ('Vitebsk', 'Vitebsk'))), ('Russia', (('Moscow', 'Moscow'),)), ('Poland', (('Warsaw', 'Warsaw'),)), ('Ukraine', (('Kiev', 'Kiev'),)), ('Lithuania', (('Vilnius', 'Vilnius'),)), ('Latvia', (('Riga', 'Riga'),)), ('Estonia', (('Tallinn', 'Tallinn'),))], default='', max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Водительское удостоверение категории В', 'Водительское удостоверение категории В'), ('Стрессоустойчивость', 'Стрессоустойчивость'), ('МС Офис', 'МС Офис'), ('Грамотная речь', 'Грамотная речь'), ('Командная работа', 'Командная работа'), ('Грамотность', 'Грамотность'), ('Корпоративная этика', 'Корпоративная этика'), ('Ведение переговоров', 'Ведение переговоров')], max_length=1000, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='specialization',
            field=models.CharField(choices=[(None, '------------'), ('Economist', 'Economist'), ('Lawyer', 'Lawyer'), ('Engineer', 'Engineer'), ('Architect', 'Architect'), ('Teacher', 'Teacher'), ('Driver', 'Driver'), ('Cook', 'Cook'), ('Seller', 'Seller'), ('Manager', 'Manager')], default='', max_length=50, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_spheres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Energetics', 'Energetics'), ('Financial_sector', 'Financial sector'), ('Chemical_industry', 'The chemical industry'), ('Art and culture', 'Art and culture'), ('Education', 'Education'), ('Medecine', 'Medicine'), ('Retail', 'Retail'), ('Car_business', 'Car business'), ('ИТ', 'IT')], max_length=103, null=True, verbose_name='Сфера деятельности компании'),
        ),
        migrations.DeleteModel(
            name='LangLevel',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='LanguageLevel',
        ),
    ]
