# Generated by Django 3.1.6 on 2021-05-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20210525_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='languages',
            field=models.ManyToManyField(related_name='applicants', to='app.LanguageLevel', verbose_name='Языки'),
        ),
    ]
