# Generated by Django 3.1.6 on 2021-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20210526_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagelevel',
            name='level',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Уровень владения'),
        ),
    ]
