# Generated by Django 3.1.6 on 2021-05-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210526_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        )
    ]
