# Generated by Django 3.1.6 on 2021-05-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20210526_0443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageLevel',
            new_name='Language',
        ),
    ]
