# Generated by Django 3.1.6 on 2021-05-26 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_remove_applicant_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='languages',
            field=models.ManyToManyField(related_name='applicant', through='app.ApplicantLanguage', to='app.Language', verbose_name='Языки'),
        ),
    ]
