# Generated by Django 3.1.6 on 2021-05-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20210526_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantlanguage',
            old_name='applicant_id',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='applicantlanguage',
            old_name='language_id',
            new_name='language',
        ),
    ]
